param(
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
    [switch]$UpdateManifest,
    [switch]$CopyToGameRoot
)

$ErrorActionPreference = 'Stop'

function Get-Adler32 {
    param([byte[]]$Bytes)

    [uint32]$a = 1
    [uint32]$b = 0

    foreach ($byte in $Bytes) {
        $a = ($a + $byte) % 65521
        $b = ($b + $a) % 65521
    }

    $value = [uint32]((($b -shl 16) + $a) -band 0xffffffff)
    return $value.ToString('x8')
}

function Get-LuaLongString {
    param([string]$Text)

    $equals = ''
    while ($Text.Contains("]$equals]")) {
        $equals += '='
    }

    return "[$equals[$Text]$equals]"
}

function Get-LuaQuotedString {
    param([string]$Text)

    $Text = $Text.Replace('\', '\\')
    $Text = $Text.Replace('"', '\"')
    $Text = $Text.Replace("`r", '\r')
    $Text = $Text.Replace("`n", '\n')
    return '"' + $Text + '"'
}

function Get-RelativeLuaModuleName {
    param(
        [string]$RootPath,
        [string]$FilePath
    )

    $rootFullPath = [System.IO.Path]::GetFullPath($RootPath).TrimEnd('\', '/') + [System.IO.Path]::DirectorySeparatorChar
    $fileFullPath = [System.IO.Path]::GetFullPath($FilePath)

    if (-not $fileFullPath.StartsWith($rootFullPath, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "File is outside root: $FilePath"
    }

    $relative = $fileFullPath.Substring($rootFullPath.Length)
    $relative = $relative.Replace('\', '/')
    return $relative.Substring(0, $relative.Length - 4)
}

$loaderPath = Join-Path $Root 'Pasthetic loader.lua'
$outputPath = Join-Path $Root 'Pasthetic allinone.lua'
$modulesRoot = Join-Path $Root 'pasthetic'
$manifestPath = Join-Path $Root 'manifest.json'

if (-not (Test-Path -LiteralPath $loaderPath)) {
    throw "Missing loader: $loaderPath"
}

if (-not (Test-Path -LiteralPath $modulesRoot)) {
    throw "Missing module directory: $modulesRoot"
}

$loader = [System.IO.File]::ReadAllText($loaderPath)
$loader = $loader -replace "`r`n", "`n"

$suffixMarker = "local ffi = require 'ffi'"
$suffixIndex = $loader.IndexOf($suffixMarker)
if ($suffixIndex -lt 0) {
    throw "Cannot find loader suffix marker: $suffixMarker"
}

$loaderSuffix = $loader.Substring($suffixIndex)
$moduleFiles = Get-ChildItem -LiteralPath $modulesRoot -Recurse -File -Filter '*.lua' |
    Sort-Object { Get-RelativeLuaModuleName -RootPath $Root -FilePath $_.FullName }

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('-- Pasthetic all-in-one generated from local split modules.')
[void]$builder.AppendLine('-- Do not edit this file by hand; regenerate it with tools/build_allinone.ps1.')
[void]$builder.AppendLine('local __pasthetic_allinone = true')
[void]$builder.AppendLine("local PASTHETIC_GIT_URL = 'https://github.com/Garagoro/Pasthetic'")
[void]$builder.AppendLine("local function log_loader_reinstall_hint()")
[void]$builder.AppendLine("    if client ~= nil and client.color_log ~= nil then")
[void]$builder.AppendLine("        client.color_log(250, 50, 75, '[Pasthetic] \0')")
[void]$builder.AppendLine("        client.color_log(255, 255, 255, 'Redownload the loader from GitHub: ' .. PASTHETIC_GIT_URL)")
[void]$builder.AppendLine("    end")
[void]$builder.AppendLine("end")
[void]$builder.AppendLine('local __pasthetic_embedded_modules = {')

foreach ($file in $moduleFiles) {
    $moduleName = Get-RelativeLuaModuleName -RootPath $Root -FilePath $file.FullName
    $source = [System.IO.File]::ReadAllText($file.FullName)
    $source = $source -replace "`r`n", "`n"
    $longString = Get-LuaLongString -Text $source
    [void]$builder.AppendLine(("    [{0}] = {1}," -f (Get-LuaQuotedString -Text $moduleName), $longString))
}

[void]$builder.AppendLine('}')
[void]$builder.AppendLine('local __pasthetic_embedded_files = {}')
[void]$builder.AppendLine('for __name, __source in pairs(__pasthetic_embedded_modules) do')
[void]$builder.AppendLine("    __pasthetic_embedded_files[__name .. '.lua'] = __source")
[void]$builder.AppendLine("    __pasthetic_embedded_files[(__name .. '.lua'):gsub('/', '\\')] = __source")
[void]$builder.AppendLine('end')
[void]$builder.AppendLine('local __pasthetic_real_readfile = readfile')
[void]$builder.AppendLine('local function __pasthetic_readfile(path)')
[void]$builder.AppendLine("    if type(path) == 'string' then")
[void]$builder.AppendLine("        local normalized = path:gsub('^%.[/\\]', '')")
[void]$builder.AppendLine('        local direct = __pasthetic_embedded_files[normalized]')
[void]$builder.AppendLine('        if direct ~= nil then return direct end')
[void]$builder.AppendLine("        local slash = normalized:gsub('\\', '/')")
[void]$builder.AppendLine('        direct = __pasthetic_embedded_files[slash]')
[void]$builder.AppendLine('        if direct ~= nil then return direct end')
[void]$builder.AppendLine("        direct = __pasthetic_embedded_files[slash:gsub('/', '\\')]")
[void]$builder.AppendLine('        if direct ~= nil then return direct end')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    if __pasthetic_real_readfile ~= nil then')
[void]$builder.AppendLine('        return __pasthetic_real_readfile(path)')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    return nil')
[void]$builder.AppendLine('end')
[void]$builder.AppendLine('local function can_read_file(path)')
[void]$builder.AppendLine('    if __pasthetic_real_readfile == nil then')
[void]$builder.AppendLine('        return false')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('    local ok, result = pcall(__pasthetic_real_readfile, path)')
[void]$builder.AppendLine("    return ok and type(result) == 'string'")
[void]$builder.AppendLine('end')
[void]$builder.AppendLine("local LOCAL_PREFIX = can_read_file('pasthetic\\core.lua') and '' or (can_read_file('pasthetic\\pasthetic\\core.lua') and 'pasthetic\\' or '')")
[void]$builder.AppendLine('local function local_path(path)')
[void]$builder.AppendLine("    if LOCAL_PREFIX == '' or type(path) ~= 'string' or path == '' then")
[void]$builder.AppendLine('        return path')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    return LOCAL_PREFIX .. path')
[void]$builder.AppendLine('end')
[void]$builder.AppendLine('local function require_pasthetic_module(name)')
[void]$builder.AppendLine('    if package ~= nil and package.loaded ~= nil then')
[void]$builder.AppendLine('        package.loaded[name] = nil')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    local source = __pasthetic_embedded_modules[name]')
[void]$builder.AppendLine("    local path = name:gsub('/', '\\') .. '.lua'")
[void]$builder.AppendLine('    if source == nil then')
[void]$builder.AppendLine('        source = __pasthetic_readfile(local_path(path))')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    if source == nil then')
[void]$builder.AppendLine("        local nested_path = 'pasthetic\\' .. path")
[void]$builder.AppendLine('        source = __pasthetic_readfile(local_path(nested_path))')
[void]$builder.AppendLine('        if source ~= nil then path = nested_path end')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    if source ~= nil then')
[void]$builder.AppendLine("        local chunk, load_error = loadstring(source, '@' .. path)")
[void]$builder.AppendLine('        if chunk == nil then log_loader_reinstall_hint(); error(load_error) end')
[void]$builder.AppendLine('        local ok, result = pcall(chunk)')
[void]$builder.AppendLine('        if not ok then log_loader_reinstall_hint(); error(result) end')
[void]$builder.AppendLine('        if package ~= nil and package.loaded ~= nil then package.loaded[name] = result end')
[void]$builder.AppendLine('        return result')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    local ok, result = pcall(require, name)')
[void]$builder.AppendLine('    if ok then return result end')
[void]$builder.AppendLine('    log_loader_reinstall_hint()')
[void]$builder.AppendLine('    error(result)')
[void]$builder.AppendLine('end')
[void]$builder.AppendLine('')
[void]$builder.Append($loaderSuffix)

$output = $builder.ToString() -replace "`r`n", "`n"
[System.IO.File]::WriteAllText($outputPath, $output, [System.Text.UTF8Encoding]::new($false))

if ($UpdateManifest) {
    if (-not (Test-Path -LiteralPath $manifestPath)) {
        throw "Missing manifest: $manifestPath"
    }

    $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json

    foreach ($entry in $manifest.files) {
        if ($null -eq $entry.path -or $entry.path -like '*..*' -or $entry.path -match '^[a-zA-Z]:') {
            continue
        }

        $targetPath = Join-Path $Root ($entry.path -replace '/', '\')
        if (-not (Test-Path -LiteralPath $targetPath)) {
            continue
        }

        $bytes = [System.IO.File]::ReadAllBytes($targetPath)
        $entry.size = [int]$bytes.Length
        $entry.checksum = Get-Adler32 $bytes
    }

    $json = $manifest | ConvertTo-Json -Compress -Depth 8
    [System.IO.File]::WriteAllText($manifestPath, $json, [System.Text.UTF8Encoding]::new($false))
}

$copiedToGameRoot = $false
if ($CopyToGameRoot) {
    $gameRoot = Split-Path -Parent $Root
    $gameOutputPath = Join-Path $gameRoot 'Pasthetic allinone.lua'
    try {
        Copy-Item -LiteralPath $outputPath -Destination $gameOutputPath -Force
        $copiedToGameRoot = $true
    } catch {
        Write-Warning "Could not copy all-in-one to game root: $($_.Exception.Message)"
    }
}

Write-Output ("Built {0} module(s) into {1}" -f $moduleFiles.Count, $outputPath)
if ($UpdateManifest) {
    Write-Output "Updated manifest.json"
}
if ($copiedToGameRoot) {
    Write-Output "Copied all-in-one to game root"
}
